config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'search#index'
  get '/poll', to: 'search#poll'

  mount Resque::Server.new, at: '/resque'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  MEETUP_GROUP_PATH = 'https://api.meetup.com/find/groups'.freeze

  def index
    @result = CacheQueryService.new(cache_params).get
  end

  def poll
    @groups = groups_data
  end

  private

  def cache_params
    {
      'key' => query_params.to_query,
      'type' => 'meetup',
      'params' => query_params.to_hash,
      'url' => MEETUP_GROUP_PATH
    }
  end

  def groups_data
    return [] if poll_params.empty? || MeetupDataService.get(poll_params[:poll_key]).nil?
    MeetupDataService.get(poll_params[:poll_key])
  end

  def poll_params
    params.permit(:poll_key)
  end

  def query_params
    params.permit(:location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetuper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<div class="page-wrapper">
  <section class="search-section">
    <%= form_tag root_path, method: :get do %>
      <%= text_field_tag :location %>
      <%= submit_tag 'Search' %>
    <% end %>
  </section>
  <section class="result-section">
  <% if @result[:async] %>
    <script>
      pollResults('<%= poll_path %>', '<%= @result[:key]%>')
    </script>
  <% else %>
      <%= render partial: 'shared/results', locals: { results: @result[:results] } %>
  <% end %>
  </section>
</div>

app/views/search/poll.js.erb
var elem = document.getElementsByClassName('result-section')[0]
<% if @groups.size > 0 %>
  elem.innerHTML = '<%= escape_javascript(render partial: "shared/results", locals: { results: @groups }) %>'
  clearInterval(window.pollInterval)
<% else %>
  elem.innerHTML = '<div>Loading...</div>'
<% end %>

app/views/shared/_results.html.erb
<table>
  <thead>
     <tr>
       <th>Photo</th>
       <th>Name</th>
       <th>Location</th>
       <th>Status</th>
       <th>Category</th>
     </tr>
   </thead>
   <tbody>
     <% results.each do |item| %>
       <tr>
         <td>
           <img src=<%= item['image'] %> alt="" />
         </td>
         <td><%= item['name'] %></td>
         <td><%= item['location'] %></td>
         <td><%= item['status'] %></td>
         <td><%= item['category'] %></td>
       </tr>
     <% end %>
   </tbody>
</table>